// react/demo/src/app.jsx
import React from 'react';
import { MyButton } from './button';
import { Button, ToggleButton, ButtonGroup, ToggleButtonGroup } from 'ilib-react';
import './app.css'

export default class App extends React.Component {
    constructor(props) {
        super(props)

        this.state = {
            disabledButton: false,
            disabledButtonInGroup: false,

            activeItem: 1
        };
    }
    render() {
        var toggleHandler = () => this.setState({ disabledButton: !this.state.disabledButton })
        var toggleInGroupHandler = () => this.setState({ disabledButtonInGroup: !this.state.disabledButtonInGroup })

        var activateHandler = (e) => this.setState({ activeItem: e.index })

        return (
            <div>
                <h1>ilib react demo</h1>

                <h2>Native component</h2>
                <MyButton style={{ background: 'red' }}>Hello World!</MyButton>

                <h2>Button component</h2>
                <Button onClick={alert.bind(null, 'green clicked')}>Hello world!</Button>
                &nbsp;
                <Button className={"greenButton"} onClick={alert.bind(null, 'clicked')}>Hello green world!</Button>

                <h2>ToggleButton component</h2>
                <Button disabled={this.state.disabledButton} onClick={alert.bind(null, 'clicked')}>
                    Hello world!
                </Button>
                &nbsp;
                <ToggleButton active={this.state.disabledButton} onClick={toggleHandler}>
                    {'< ' + (this.state.disabledButton ? 'enable' : 'disable')}
                </ToggleButton>

                <h2>ButtonGroup component</h2>
                <ButtonGroup>
                    <Button disabled={this.state.disabledButtonInGroup} onClick={alert.bind(null, 'clickedInGroup')}>
                        Hello world!
                    </Button>
                    <ToggleButton active={this.state.disabledButtonInGroup} onClick={toggleInGroupHandler}>
                        {'< ' + (this.state.disabledButtonInGroup ? 'enable' : 'disable')}
                    </ToggleButton>
                </ButtonGroup>

                <h2>ToggleButtonGroup component</h2>
                <ToggleButtonGroup items={[1, 2, 3]} active={this.state.activeItem} onActivate={activateHandler}></ToggleButtonGroup>
                <ToggleButtonGroup items={[1, 2, 3, 4, 5]} active={this.state.activeItem} onActivate={activateHandler}>{{
                    default: (data) => <ToggleButton className={data.index === 2 ? 'greenButton' : ''} active={data.active} onClick={data.activate}><i>{data.item}</i></ToggleButton>
                }}</ToggleButtonGroup>
        </div>
        )
    }
}

// angular/demo/src/app.component.ts
/* tslint:disable:component-selector */

import {
    Component
} from '@angular/core';

@Component({
    selector: 'my-app',
    styles: [`
    b { color: brown; }
    .greenButton { border: 1px solid green; }
`],
    template: `
    <h1>ilib angular demo</h1>

    <h2>Native component</h2>
    <my-button [disabled]="true"><template myTemplate let-data myTemplateOf="default">> {{data.text}} <</template></my-button>

    <h2>Button component</h2>
    <button ilib-button (onClick)="clicked('g')"><b>Hello World Again!</b></button>
    <button ilib-button class="greenButton" (onClick)="clicked('g1')"><b>Hello Green World!</b></button>

    <h2>ToggleButton component</h2>
    <button ilib-button #btn [disabled]="false" (onClick)="clicked('btn')">Hello World!</button>
    <button ilib-toggle_button [(active)]="btn.disabled">
        < {{btn.disabled ? 'enable' : 'disable'}}
    </button>
    
    <h2>ButtonGroup component</h2>
    <div ilib-button_group>
        <button ilib-button #btnInGroup [disabled]="false" (onClick)="clicked('btnInGroup')">Hello World!</button>
        <button ilib-toggle_button [(active)]="btnInGroup.disabled">
            < {{btnInGroup.disabled ? 'enable' : 'disable'}}
        </button>
    </div>
    
    <h2>RadioGroup component</h2>
    <div ilib-toggle_button_group [items]="[1, 2, 3]" [(active)]="activeItem"></div>
    <div ilib-toggle_button_group [items]="[1, 2, 3, 4, 5]" [(active)]="activeItem">
        <button ilib-toggle_button [_reactiveMode]="true" *ilTemplate="let data" [active]="data.active" (onClick)="data.activate($event)" [class.greenButton]="data.index === 2">
            <i>{{data.item}}</i>
        </button>
    </div>
`
})
export class AppComponent {
    activeItem = 1

    constructor() { }

    clicked(type) {
        alert(`clicked: ${type}`)
    }
}
